import {
  FunctionComponent,
  ReactElement
} from 'react'
import FeatureCard from '@/components/FeatureCard'
const Features: FunctionComponent = (): ReactElement => (
  <section className='py-16'>
    <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
      <div className='lg:text-center'>
        <h2 className='text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-light'>
          Key Features
        </h2>
        <p className='mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto'>
          GeniGPT offers a suite of powerful features to help you detect and enhance AI-generated content.
        </p>
      </div>
      <div className='mt-10'>
        <dl className='space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10'>
          <FeatureCard
            title='AI Detection'
            desc='Analyze your content and receive a detailed report on whether it was generated by an AI or a human.'
            svg='M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z'
          />
          <FeatureCard
            title='Creative Enhancement'
            desc='Receive suggestions to improve and refine your content, making it more engaging and unique.'
            svg='M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z'
          />
          <FeatureCard
            title='Seamless Account Management'
            desc='Easily manage your account, subscriptions, and trials, enjyoing a smooth, no-hassle experience.'
            svg='M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3'
          />
          <FeatureCard
            title='Responsive and User Friendly'
            desc='Enjoy a visually stunning and intuitive experience on any device with a modern and responsive design.'
            svg='M13 10V3L4 14h7v7l9-11h-7z'
          />
        </dl>
      </div>
    </div>
  </section>
)
export default Features